# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MadCity Folders
email: madcityfolders@gmail.com
description: "MadCity Folders is Madison, WI's origami group."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://madcityfolders.org" # the base hostname & protocol for your site
twitter_username: madcityfolders
github_username:  madcityfolders

# Build settings
markdown: kramdown

# Pretty permalinks
permalink: pretty
