# Site settings
title: MadCity Folders
email: madcityfolders@gmail.com
description: "MadCity Folders is a diverse group of origami enthusiasts who meet monthly to teach, share, and practice the art of origami."
baseurl: ""
twitter_username: madcityfolders
github_username:  madcityfolders

# Build settings
markdown: kramdown

# Pretty permalinks
permalink: pretty
