# Site settings
title: MadCity Folders
email: madcityfolders@gmail.com
description: "MadCity Folders is Madison, WI's origami group."
baseurl: ""
twitter_username: madcityfolders
github_username:  madcityfolders

# Build settings
markdown: kramdown

# Pretty permalinks
permalink: pretty
