# Site settings
title: MadCity Folders
email: madcityfolders@gmail.com
description: "MadCity Folders is Madison's Origami group. We have meetings monthly, and a crease-pattern server in the works"
baseurl: ""
url: ""
#twitter_username: jekyllrb
github_username: MadCityFolders

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
