backend:
  name: git-gateway
  branch: master

media_folder: assets/images/uploads
collections:
  - label: Pages
    name: pages
    files:
      - label: "Home Page"
        name: index
        file: "index.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Events Page"
        name: events
        file: "events.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Gallery Page"
        name: gallery
        file: "gallery.html"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
